'use strict';

const fs = require('node:fs');
const { ROLE_EXPECTATIONS } = require('../core/role-sanity.js');

const CAT7_FIELDS = ['focus', 'issue', 'intent', 'motivation', 'commitment', 'perspective', 'mood'];

const ROLE_PRESETS = Object.freeze({
  writer:        { focus: 2.0, issue: 1.0, intent: 2.5, motivation: 1.5, commitment: 1.0, perspective: 0.5, mood: 0.6 },
  reviewer:      { focus: 1.0, issue: 2.5, intent: 1.2, motivation: 0.8, commitment: 2.0, perspective: 0.5, mood: 0.6 },
  'test-writer': { focus: 1.2, issue: 2.0, intent: 1.0, motivation: 0.8, commitment: 2.5, perspective: 0.5, mood: 0.6 },
  auditor:       { focus: 1.0, issue: 2.0, intent: 0.8, motivation: 0.8, commitment: 1.5, perspective: 2.5, mood: 0.6 },
  generator:     { focus: 2.5, issue: 1.0, intent: 2.0, motivation: 1.2, commitment: 1.0, perspective: 0.5, mood: 0.6 },
  spec:          { focus: 2.0, issue: 1.0, intent: 2.5, motivation: 1.5, commitment: 1.2, perspective: 0.5, mood: 0.6 },
  generic:       { focus: 1.0, issue: 1.0, intent: 1.0, motivation: 1.0, commitment: 1.0, perspective: 1.0, mood: 1.0 },
});

const ADAPTER_DEFAULTS = Object.freeze({
  anthropic: { modelName: 'claude-haiku-4-5-20251001', envKey: 'ANTHROPIC_API_KEY' },
  openai:    { modelName: 'gpt-4o-mini',               envKey: 'OPENAI_API_KEY' },
  ollama:    { modelName: 'llama3.2:3b',               envKey: null },
  mistral:   { modelName: 'mistral-small-latest',      envKey: 'MISTRAL_API_KEY' },
});

function buildToml({ peerName, role, group, adapter, modelName, costCap }) {
  const weights = ROLE_PRESETS[role] || ROLE_PRESETS.generic;
  const lines = [];
  lines.push(`# Generated by \`xmesh-agent init ${peerName}\``);
  lines.push(`# Role: ${role} — α weights tuned for ${role === 'generic' ? 'general use (uniform 1.0)' : `${role} priorities`}`);
  lines.push('');
  lines.push('[identity]');
  lines.push(`name = "${peerName}"`);
  lines.push(`role = "${role}"`);
  lines.push('');
  lines.push('[mesh]');
  lines.push(`group = "${group}"`);
  lines.push('# relay = "wss://sym-relay.onrender.com"   # uncomment for WAN; LAN Bonjour is default');
  lines.push('# relay_token = "..."                       # or set SYM_RELAY_TOKEN in env');
  lines.push('');
  lines.push('[role_weights]');
  for (const f of CAT7_FIELDS) lines.push(`${f} = ${weights[f]}`);
  lines.push('');
  lines.push('[model]');
  lines.push(`adapter = "${adapter}"`);
  lines.push(`model_name = "${modelName}"`);
  lines.push('max_tokens_per_call = 1024');
  if (adapter === 'ollama') {
    lines.push('# base_url = "http://localhost:11434"   # default; override for remote Ollama box');
  } else {
    const envKey = ADAPTER_DEFAULTS[adapter].envKey;
    lines.push(`# api_key reads from ${envKey} env var (preferred); inline below only if you must`);
    lines.push('# api_key = "..."');
  }
  lines.push('');
  lines.push('[context]');
  lines.push('k_lineage = 3');
  lines.push('n_own = 5');
  lines.push('n_group = 10');
  lines.push('max_context_tokens = 8000');
  lines.push('');
  lines.push('[budget]');
  lines.push('max_wakes_per_minute = 10');
  lines.push('max_wakes_per_hour = 100');
  lines.push('max_wakes_per_day = 1000');
  lines.push(`max_cost_usd_per_hour = ${(costCap / 2).toFixed(2)}`);
  lines.push(`max_cost_usd_per_day = ${(costCap * 2).toFixed(2)}`);
  lines.push(`max_cost_usd_per_run = ${costCap.toFixed(2)}`);
  lines.push('');
  lines.push('[safety]');
  lines.push('cycle_depth = 5');
  lines.push('approval_gates = "default"');
  lines.push('');
  lines.push('[routing]');
  lines.push('# broadcast (default; every peer sees responses) | targeted | auto');
  lines.push('response_routing = "broadcast"');
  lines.push('');
  lines.push('[attach]');
  lines.push('mode = "headless"');
  lines.push('');
  return lines.join('\n');
}

function parseArgs(args) {
  const positional = args.filter((a) => !a.startsWith('--'));
  const peerName = positional[0];
  const flag = (name, fallback) => {
    const i = args.indexOf(`--${name}`);
    if (i === -1) return fallback;
    return args[i + 1];
  };
  return {
    peerName,
    role: flag('role', 'generic'),
    group: flag('group', 'xmesh-default'),
    adapter: flag('adapter', 'anthropic'),
    model: flag('model', null),
    output: flag('out', null),
    force: args.includes('--force'),
    costCap: Number(flag('cost-cap', '5')),
  };
}

function init(args, { out = process.stdout, err = process.stderr } = {}) {
  const opts = parseArgs(args);
  if (!opts.peerName) {
    err.write('xmesh-agent init: missing <peer-name> argument\n');
    err.write('usage: xmesh-agent init <peer-name> [--role writer|reviewer|test-writer|auditor|generator|spec|generic] [--group <name>] [--adapter anthropic|openai|ollama] [--model <name>] [--out <path>] [--cost-cap <usd>] [--force]\n');
    return 2;
  }
  if (!ADAPTER_DEFAULTS[opts.adapter]) {
    err.write(`xmesh-agent init: unsupported adapter "${opts.adapter}" (supported: anthropic | openai | ollama)\n`);
    return 2;
  }
  if (!Number.isFinite(opts.costCap) || opts.costCap <= 0) {
    err.write(`xmesh-agent init: --cost-cap must be a positive number (got: ${opts.costCap})\n`);
    return 2;
  }
  const knownRoles = Object.keys(ROLE_PRESETS);
  if (!knownRoles.includes(opts.role)) {
    err.write(`xmesh-agent init: role "${opts.role}" not in known presets (using generic α weights). Known roles: ${knownRoles.join(', ')}\n`);
  }
  const adapterDefaults = ADAPTER_DEFAULTS[opts.adapter];
  const modelName = opts.model || adapterDefaults.modelName;
  const outputPath = opts.output || `${opts.peerName}.toml`;
  const toml = buildToml({
    peerName: opts.peerName,
    role: opts.role,
    group: opts.group,
    adapter: opts.adapter,
    modelName,
    costCap: opts.costCap,
  });
  try {
    fs.writeFileSync(outputPath, toml, { flag: opts.force ? 'w' : 'wx' });
  } catch (e) {
    if (e.code === 'EEXIST') {
      err.write(`xmesh-agent init: ${outputPath} already exists — use --force to overwrite\n`);
      return 1;
    }
    throw e;
  }
  out.write(`wrote ${outputPath}\n`);
  out.write(`  peer:    ${opts.peerName}\n`);
  out.write(`  role:    ${opts.role}${ROLE_EXPECTATIONS[opts.role] ? ' (known role; α weights tuned)' : ' (generic α weights)'}\n`);
  out.write(`  group:   ${opts.group}\n`);
  out.write(`  adapter: ${opts.adapter} / ${modelName}\n`);
  out.write(`  budget:  $${opts.costCap.toFixed(2)} per run\n`);
  out.write('\nnext steps:\n');
  if (adapterDefaults.envKey) out.write(`  1. export ${adapterDefaults.envKey}=...\n`);
  out.write(`  ${adapterDefaults.envKey ? '2' : '1'}. xmesh-agent dry-run --config ${outputPath}\n`);
  out.write(`  ${adapterDefaults.envKey ? '3' : '2'}. xmesh-agent run --config ${outputPath}\n`);
  return 0;
}

module.exports = { init, buildToml, parseArgs, ROLE_PRESETS, ADAPTER_DEFAULTS };
