#!/usr/bin/env bash
# Helper for cross-host runbook — writes per-peer agent.toml with a shared
# timestamped group. Run with: ./examples/xhost-helper.sh alice > /tmp/alice.toml
set -euo pipefail

if [ $# -lt 1 ]; then
  echo "usage: $0 <peer-name>" >&2
  echo "optional env: XMESH_SMOKE_GROUP (defaults to xmesh-xhost-<now>)" >&2
  exit 2
fi

peer="$1"
group="${XMESH_SMOKE_GROUP:-xmesh-xhost-$(date +%Y%m%d%H%M%S)}"

cat <<EOF
# Generated by xhost-helper.sh — peer=${peer} group=${group}

[identity]
name = "${peer}"
role = "verifier"

[mesh]
group = "${group}"

[role_weights]
focus = 1.5
issue = 1.5
intent = 1.5
motivation = 1.0
commitment = 1.5
perspective = 0.5
mood = 0.8

[model]
adapter = "anthropic"
model_name = "claude-haiku-4-5-20251001"
max_tokens_per_call = 400

[context]
k_lineage = 3
n_own = 5
n_group = 10
max_context_tokens = 4000

[budget]
max_wakes_per_minute = 5
max_wakes_per_hour = 30
max_wakes_per_day = 100
max_cost_usd_per_hour = 0.50
max_cost_usd_per_day = 1.00
max_cost_usd_per_run = 1.00

[safety]
cycle_depth = 5
approval_gates = "default"

[attach]
mode = "headless"
EOF

echo "# group: ${group}" >&2
echo "# share this group name with the other host before it starts" >&2
